apiVersion: v1
kind: Template
metadata:
  name: presentation-template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: presentation
    name: presentation
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: presentation:latest
    source:
      contextDir: Presentation
      git:
        uri: https://github.com/RHsyseng/FIS2-MSA.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: jboss-eap70-openshift:1.4
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: MxjIZoWLfY9ySgCEc5mo
      type: GitHub
    - generic:
        secret: 2Qs5dlAL3FQGSlp5huoa
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: presentation
    name: presentation
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: presentation:latest
      name: latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: presentation
    name: presentation
  spec:
    replicas: 1
    selector:
      app: presentation
      deploymentconfig: presentation
    template:
      metadata:
        labels:
          app: presentation
          deploymentconfig: presentation
      spec:
        containers:
        - imagePullPolicy: IfNotPresent
          name: presentation
          ports:
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - presentation
        from:
          kind: ImageStreamTag
          name: presentation:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: presentation
    name: presentation
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      app: presentation
      deploymentconfig: presentation
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      app: presentation
    name: presentation
  spec:
    host: ${ROUTE_URL}
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: presentation
      weight: 100
    wildcardPolicy: None
parameters:
  - name: ROUTE_URL
    description: Route Address for Presentation
    value: presentation.bxms.ose
