apiVersion: v1
kind: Template
metadata:
  name: product-service-template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: product-service
    name: product-service
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: product-service:latest
    source:
      contextDir: Product
      git:
        uri: https://github.com/RHsyseng/FIS2-MSA.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: jboss-eap70-openshift:1.4
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: MxjIZoWLfY9ySgCEc5mo
      type: GitHub
    - generic:
        secret: 2Qs5dlAL3FQGSlp5huoa
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: product-service
    name: product-service
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: product-service:latest
      name: latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: product-service
    name: product-service
  spec:
    replicas: 1
    selector:
      app: product-service
      deploymentconfig: product-service
    template:
      metadata:
        labels:
          app: product-service
          deploymentconfig: product-service
      spec:
        containers:
        - env:
          - name: MYSQL_PASSWORD
            value: password
          - name: MYSQL_USER
            value: product
          imagePullPolicy: IfNotPresent
          name: product-service
          ports:
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - product-service
        from:
          kind: ImageStreamTag
          name: product-service:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: product-service
    name: product-service
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      app: product-service
      deploymentconfig: product-service
