apiVersion: v1
kind: Template
metadata:
  name: sales-service-template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: sales-service
    name: sales-service
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: sales-service:latest
    source:
      contextDir: Sales
      git:
        uri: https://github.com/RHsyseng/FIS2-MSA.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: jboss-eap70-openshift:1.4
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: MxjIZoWLfY9ySgCEc5mo
      type: GitHub
    - generic:
        secret: 2Qs5dlAL3FQGSlp5huoa
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: sales-service
    name: sales-service
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: ${DOCKER_HOST}:${DOCKER_PORT}/${PROJECT_NAME}/sales-service:latest
      name: latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: sales-service
    name: sales-service
  spec:
    replicas: 1
    selector:
      app: sales-service
      deploymentconfig: sales-service
    template:
      metadata:
        labels:
          app: sales-service
          deploymentconfig: sales-service
      spec:
        containers:
        - env:
          - name: MYSQL_PASSWORD
            value: password
          - name: MYSQL_USER
            value: sales 
          imagePullPolicy: IfNotPresent
          name: sales-service
          ports:
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - sales-service
        from:
          kind: ImageStreamTag
          name: sales-service:latest
          namespace: ${PROJECT_NAME}
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: sales-service
    name: sales-service
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      app: sales-service
      deploymentconfig: sales-service
parameters:
  - name: DOCKER_HOST
    description: Docker Registry Host IP
    value: 172.30.206.185
  - name: DOCKER_PORT
    description: Docker Registry Host Port
    value: "5000"
  - name: PROJECT_NAME
    description: OpenShift Parent Project Name
    value: fis2-msa
