apiVersion: v1
kind: Template
metadata:
  name: warehouse-service-template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: warehouse-service
    name: warehouse-service
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: warehouse-service:latest
    source:
      contextDir: Warehouse
      git:
        uri: https://github.com/RHsyseng/FIS2-MSA.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: fis-java-openshift:2.0
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: MxjIZoWLfY9ySgCEc5mo
      type: GitHub
    - generic:
        secret: 2Qs5dlAL3FQGSlp5huoa
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: warehouse-service
    name: warehouse-service
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: ${DOCKER_HOST}:${DOCKER_PORT}/${PROJECT_NAME}/warehouse-service:latest
      name: latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: warehouse-service
    name: warehouse-service
  spec:
    replicas: 1
    selector:
      app: warehouse-service
      deploymentconfig: warehouse-service
    template:
      metadata:
        labels:
          app: warehouse-service
          deploymentconfig: warehouse-service
      spec:
        containers:
        - env:
          - name: ACTIVEMQ_BROKER_PASSWORD
            value: password
          - name: ACTIVEMQ_BROKER_USERNAME
            value: mquser
          - name: ACTIVEMQ_SERVICE_HOST
            value: broker-amq-tcp
          - name: ACTIVEMQ_SERVICE_PORT
            value: "61616"
          imagePullPolicy: IfNotPresent
          name: warehouse-service
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 9091
            protocol: TCP
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - warehouse-service
        from:
          kind: ImageStreamTag
          name: warehouse-service:latest
          namespace: ${PROJECT_NAME}
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: warehouse-service
    name: warehouse-service
  spec:
    ports:
    - name: jolokia
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      app: warehouse-service
      deploymentconfig: warehouse-service
parameters:
  - name: DOCKER_HOST
    description: Docker Registry Host IP
    value: 172.30.206.185
  - name: DOCKER_PORT
    description: Docker Registry Host Port
    value: "5000"
  - name: PROJECT_NAME
    description: OpenShift Parent Project Name
    value: fis2-msa
